#################################################################################################################
#
# IMPORTANT: This docker configuration must be use only for local execution and test purposes. PLEASE NOT APPLY THIS
# DOCKER DEPLOYMENT IN ANY CLOUD SERVER.
#
#################################################################################################################


version: '3.0'

services:
##################################################################################################################
############################################ Database container ##################################################
  db:
    image: mysql:5.7
    container_name: cpl-mysql
    volumes:
# If you have some data and structure already built, then you can add to mysql data volume, if not then keep this
# configuration.
    - db_data:/var/lib/mysql
    restart: always
# Update DB environment variables with your own values
    environment:
      MYSQL_ROOT_PASSWORD: cplrootsuser
      MYSQL_DATABASE: cpl_users
      MYSQL_USER: cpluser
      MYSQL_PASSWORD: cplpassword

##################################################################################################################
############################################ Application container ################################################
  cpl-user-api:
    image: tomcat:8
# Update container name with your own project proper container name (project-service-type)
    container_name: cpl-user-api
# Update this volume link with your own .war generated file
    volumes:
      - /media/jhonnyquest/Data2/complaints/cpl-user-be-api/target/cpl.user.be.api.war:/usr/local/tomcat/webapps/api.war
    restart: always
# Database must be linked to the project to be sure that they are in the same docker network
    links:
      - db
    depends_on:
      - db
# You should create your own env variables to setup your app
    environment:
      USERS_DB_URL: jdbc:mysql://db:3306/cpl_users
      USERS_JDBC_USERNAME: cpluser
      USERS_JDBC_PASSWORD: cplpassword
# You must be sure that each application is dispatched by a different port to avoid service crash
    ports:
      - 7080:8080
volumes:
  db_data: